name: discover
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  smooth_page_indicator: 2.0.1
  shared_preferences: ^2.5.3
  google_fonts: ^6.2.1
  supabase_flutter: ^2.9.1
  flutter_dotenv: ^6.0.0
  fpdart: ^1.1.1
  google_sign_in: ^6.1.5
  persistent_bottom_nav_bar_v2: ^6.1.0
  flutter_map: ^8.1.1
  url_launcher: ^6.3.1
  latlong2: ^0.9.1
  cached_network_image: ^3.4.1
  animations: ^2.0.11
  http: ^1.4.0
  intl: ^0.20.2
  mocktail: ^1.0.4
  image_picker: ^1.1.2
  mime: ^2.0.0
  path: ^1.9.1
  permission_handler: ^12.0.1
  geolocator: ^14.0.2
  flutter_polyline_points: ^3.0.1
  flutter_launcher_icons: ^0.14.4
  shimmer: ^3.0.0
  google_mlkit_image_labeling: ^0.14.1
  connectivity_plus: ^6.1.5
  internet_connection_checker: ^3.0.1
  showcaseview: ^4.0.1
  camera: ^0.11.2+1
  image_gallery_saver_plus: ^4.0.1
  uuid: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: true
  ios: true
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/app_icon.png"
  image_path_ios: "assets/icons/app_icon.png"
  image_path: "assets/icons/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/levels/
    - assets/data/
    - assets/avatar/
    - assets/shop/
    - assets/background/
    - assets/characters/
    - assets/stickers/
    - .env